import boto3
import botocore
import os
import sys
import threading
import time

from .generate_metadata import regenerate_metadata_files
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from enum import Enum
from itertools import product
from rich.console import Console
from rich.progress import Progress, TaskID
from rich.text import Text
from typing import Optional, Dict, List, Tuple

MAX_WORKERS = 30
TESTS_LOCATION = os.path.join(os.path.dirname(__file__), "CustomTests.yaml")
# Operations (beyond get_/list_/describe_) that accept a DryRun flag, generated by
# introspecting every service model's input shapes. AWS performs the full IAM
# permission check for a DryRun call before it does anything else, and always
# responds with either DryRunOperation (permission granted) or UnauthorizedOperation
# (denied) instead of actually executing the request - so these are safe to call as
# long as we force DryRun=True ourselves rather than trusting injected args.
#
# Computed fresh from whatever botocore is currently installed every time this module
# is imported (also refreshes ErrorShapes.yaml/DryRunOperations.yaml on disk as a
# side effect, best-effort) rather than trusting a possibly-stale checked-in copy -
# AWS adds services and operations constantly, this is cheap (well under a second,
# no network calls), so there's no reason to make freshness an opt-in flag.
_ERROR_SHAPES, DRY_RUN_OPERATIONS = regenerate_metadata_files()

TEST_FAILED_STRINGS = [
    "AccessDenied",
    "Unauthorized",
    "Forbidden",
    "NotAuthorized",
    "AuthorizationError",
    "InsufficientPrivileges",
    "MissingAuthenticationToken",
]


class TestStatus(Enum):
    SUCCEEDED = 0
    FAILED = 1
    ERRORED = 2


class InvalidRegionError(Exception):
    """
    Custom error for edge case when user specifies a region filter and one of the services is not available in the regions that match the filter
    """

    def __init__(self, service, region):
        super().__init__(f"Invalid region filter for {service} service: {region}")


@dataclass
class OperationPermissions:
    """
    Simple data structure to contain the results of a single permissions test
    We store things here for each individual test to avoid the overhead to 15 threads trying
    to update the same object at the same time
    """

    name: str
    region: str
    status: TestStatus
    results: Optional[dict]
    error: Optional[Exception]


@dataclass
class OperationPermissionsByRegion:
    """
    Dataclass to store success/failure of a boto3 client operation by region
    Each set will contain the regions that succeeded/failed/errored for the operation
    """

    name: str
    regions_tested: set
    succeeded: List[Optional[OperationPermissions]]
    failed: List[Optional[OperationPermissions]]
    errored: List[Optional[OperationPermissions]]


class Service:
    def __init__(
        self,
        service: str,
        session: boto3.session.Session,  # pyright: ignore
        executor: Optional[ThreadPoolExecutor],
        regions: Optional[List[str]] = None,
        injected_args: Optional[Dict[str, List[dict]]] = None,
        timeout: int = 5,  # TODO make this a CLI arg?
        retries: int = 0,
        progress: Optional[Progress] = None,
        task_id: Optional[TaskID] = None,
        status_text: Optional[Text] = None,
        console: Optional[Console] = None,
    ):
        """
        Wrapper around boto3 client to track resources and tests

        :service: boto3 service name
        :session: boto3 session object, will create a bare client if not provided. Useful for credential refreshing
        :regions: list of regions to test, partial matches are accepted (i.e. ['us', 'eu-west'] will test all us and eu-west regions)
        :injected_args: dictionary of arguments to inject into boto3 calls, this is loaded from a YAML file in the provider module
            the format for injected_args is:
            { '$SERVICE_NAME': [
                { 'operation_name': {
                    'args': [$LIST,$OF,$ARGS],
                    'kwargs': { '$KEY': '$VALUE', }
                },
            ]}
            The reserved key '_endpoints' (not a real service name, so it can't collide)
            optionally maps service name to a custom endpoint_url to use instead of the
            default one: { '_endpoints': { '$SERVICE_NAME': '$ENDPOINT_URL' } }
        :executor: A ThreadPoolExecutor to do bulk testing in parallel
        :timeout: how long to wait for a connection to AWS
        :retries: how many times to retry the AWS connection before erroring
        :progress: an optional rich Progress instance to advance as operations complete
        :task_id: the TaskID within :progress: to advance. Both must be supplied
            together; if omitted, no progress reporting happens (used by callers like
            tests that don't need it).
        :status_text: an optional rich Text instance to update with which operation is
            currently being tested. Kept separate from the progress bar's own task
            description so the bar's row stays a fixed width - updating it in place as
            part of the task description made the bar visibly bounce/flicker as the
            "service->operation in region" text grew and shrank.
        :console: an optional rich Console to route diagnostic messages (connection
            timeouts, unhandled exceptions) through instead of a raw print(). A raw
            print() from a worker thread while a Live display (the progress bars) is
            active writes straight to the terminal without coordinating with it,
            which is what causes the flicker/corruption - console.print() is
            Live-aware and safe to call concurrently. Falls back to plain print() to
            stderr if omitted (e.g. in tests, or the bare __main__ usage).
        """
        self.service_name = service
        self.session = session
        executor = executor or ThreadPoolExecutor(1)
        self.executor = executor
        self.progress = progress
        self.task_id = task_id
        self.status_text = status_text
        self.console = console
        self._progress_lock = threading.Lock()
        self.config = botocore.client.Config(  # pyright: ignore
            connect_timeout=timeout, retries={"max_attempts": retries}
        )
        # TODO move these options to a file?
        # If you feel like spending a lot of money you can remove this
        self._operation_safety_filters = {
            "get_",
            "list_",
            "describe_",
        }  # these calls are safe and won't incur charges (probably)

        self.injected_args = injected_args or {}

        # Reserved top-level key in the injected_args YAML (alongside the normal
        # per-service operation rules) for pointing a service's clients at a
        # non-standard endpoint instead of the default public one - e.g. testing
        # against a beta/gamma endpoint, which is sometimes not covered by the same
        # CloudTrail logging as the standard endpoint. No real AWS service is named
        # "_endpoints", so this can't collide with a service's own rule list.
        # { '_endpoints': { '$SERVICE_NAME': '$ENDPOINT_URL' } }
        self.endpoint_url = self.injected_args.get("_endpoints", {}).get(service)  # pyright: ignore

        self.regions = self.session.get_available_regions(service)

        # except AttributeError:  # Some services don't have regions
        #    self.regions = ['aws-global']

        self.regions = self.regions or ["aws-global"]

        if regions:  # apply region filter
            regions = list(regions)
            regions.append("aws-global")  # Always keep global services in scope
            self.regions = [
                region
                for region_filter, region in product(regions, self.regions)
                if region_filter in region
            ]

        if (
            len(self.regions) > 0
        ):  # this could be more DRY but I like how explicit this is
            # "aws-global" is a label we made up for filtering/reporting purposes when
            # get_available_regions() returns nothing (see the fallback above) - it is
            # NOT a real AWS region, and passing it straight to session.client()
            # produces a bogus hostname like bedrock-agent.aws-global.amazonaws.com
            # that never resolves, causing a real (and slow: the full connect_timeout
            # every time) ConnectTimeoutError for every operation. Services actually
            # missing from get_available_regions() fall into two very different
            # buckets: some (e.g. billing, ce) have a genuine global endpoint that
            # botocore's endpoint-ruleset resolution figures out correctly given ANY
            # real region name; others (e.g. bedrock-agent) are simply regional
            # services not yet reflected in botocore's legacy partition data, and need
            # an actual region to resolve at all. Substituting a real region name (the
            # session's configured one, or us-east-1) lets botocore's ruleset engine
            # sort out which case applies instead of us guessing - confirmed live: the
            # exact same "aws-global" fallback fixes bedrock-agent (was: always timed
            # out; now: resolves and returns real data) while leaving already-working
            # global services like billing/ce unaffected.
            fallback_region = self.session.region_name or "us-east-1"
            self.clients = [
                session.client(
                    service,
                    region_name=region if region != "aws-global" else fallback_region,
                    config=self.config,
                    endpoint_url=self.endpoint_url,
                )
                for region in self.regions
            ]
        else:
            # self.clients = [session.client(service, config=self.config, region_name="aws-global")]
            raise InvalidRegionError(
                self.service_name, regions
            )  # Edge case where a region filter excludes all regions where the service is available

        self.method_map = self.clients[
            0
        ].meta.method_to_api_mapping  # sugar, unused unless I decide to start outputting the AWS permission name instead of the boto3 function name

        self.operations = []
        self.operations = [
            op
            for pattern, op in product(
                self._operation_safety_filters, self.method_map.keys()
            )
            if op.startswith(pattern)
        ]

        # Mutating operations we're willing to call ONLY because they support DryRun -
        # AWS runs the full IAM permission check for a DryRun call before doing anything
        # else, and always responds with DryRunOperation (permission granted) or
        # UnauthorizedOperation (denied) instead of executing the request for real.
        # An operation only makes it into scope here if it's BOTH named EXACTLY as a
        # rule key in injected_args (the user has opted in, same YAML mechanism as
        # CustomTests.yaml - deliberately exact match, not the partial match
        # _find_injected_rule/_get_custom_args use for convenience kwargs, since a
        # short generic rule like "create_ipam" would otherwise also sweep in
        # unrelated operations like create_ipam_policy that need other args we never
        # supplied) AND confirmed by DRY_RUN_OPERATIONS (generated from the actual
        # botocore service model) to really support DryRun. Neither alone is trusted:
        # a YAML entry can't add scope for an operation that doesn't truly support
        # DryRun, and support for DryRun alone doesn't add scope without an explicit
        # opt-in - this is what protects against another Shield-style surprise
        # mutation/charge.
        injected_rule_names = {
            list(rule.keys())[0]
            for rule in self.injected_args.get(self.service_name, [])
        }
        self.dry_run_operations = set()
        for entry in DRY_RUN_OPERATIONS.get(self.service_name, []):
            op = entry["operation"]
            if op in self.operations or op not in self.method_map:
                continue
            elif op in injected_rule_names:
                self.dry_run_operations.add(op)
                self.operations.append(op)

    @staticmethod
    def classify_client_error(error: botocore.exceptions.ClientError) -> TestStatus:  # pyright: ignore
        """
        Decide whether a ClientError raised by a boto3 call represents a permissions
        failure (FAILED) or some other kind of error we hit only because we have
        permission to reach the operation in the first place (SUCCEEDED) - auth checks
        always happen before any other validation/business logic on AWS's end, so any
        non-auth error means we were authorized.

        A 403 HTTP status is always treated as a permissions failure regardless of the
        error code string, since some services return 403 with a nonstandard code. For
        everything else we fall back to matching the error code against
        TEST_FAILED_STRINGS, since a handful of auth-denial codes don't carry a 403
        (see ErrorShapes.yaml for what's been observed across every AWS service model).

        :error: the ClientError raised by the boto3 call

        :returns: TestStatus.FAILED or TestStatus.SUCCEEDED
        """
        status_code = error.response.get("ResponseMetadata", {}).get("HTTPStatusCode")
        if status_code == 403:
            return TestStatus.FAILED

        error_code = error.response["Error"]["Code"]
        if any(string in error_code for string in TEST_FAILED_STRINGS):
            return TestStatus.FAILED

        return TestStatus.SUCCEEDED  # Hit an error that isn't related to auth, this is a success because auth errors always trigger first

    def test_permission(
        self, operation: str, client: object, *args, **kwargs
    ) -> OperationPermissions:
        """
        Test if the client has permission to run the given operation.
        Args can be injected via args and kwargs, we set these in the YAML to avoid accidentally modifying the infrastructure.
        If we brute forced out the args and just blindly re-ran functions, we could cause damage to the infrastructure (just creating/updating and deleting resources willy nilly)

        :operation: boto3 client function to test
        :client: boto3 client object
        :args: arguments to pass to the boto3 call
        :kwargs: keyword arguments to pass to the boto3 call

        :returns: OperationPermissions object
        """
        region = client.meta.region_name  # pyright: ignore
        status: TestStatus
        results = None
        error = None
        try:
            results = getattr(client, operation)(
                *args, **kwargs
            )  # invoke function from strings
            status = TestStatus.SUCCEEDED
        except (
            botocore.exceptions.ParamValidationError,  # pyright: ignore
            botocore.exceptions.NoAuthTokenError,  # pyright: ignore
            botocore.exceptions.EndpointResolutionError,  # pyright: ignore
        ) as e:  # Couldn't even construct the request, no point in testing it. This
            # covers normal missing-argument errors (ParamValidationError) as well as
            # services like cloudfront-keyvaluestore whose endpoint URL depends on a
            # caller-supplied identifier (e.g. KvsARN) that's resolved client-side,
            # before any network call - a different failure mode with the same "we
            # never even reached AWS" meaning.
            status = TestStatus.ERRORED
            error = e
        except botocore.exceptions.ClientError as e:  # pyright: ignore
            status = self.classify_client_error(e)
            error = e
        return OperationPermissions(
            name=operation, region=region, status=status, results=results, error=error
        )

    def _find_injected_rule(self, operation) -> Optional[dict]:
        """
        Locate the first injected_args rule (from the serialized YAML structure) whose name
        partial-matches the given operation, on a "first found" basis. This means you can make
        a rule that applies to all 'describe' operations by setting the operation name in the
        YAML to 'describe'. If you want to override this case then you must place the
        overriding rule ABOVE the generic rule. i.e.
        - describe_specific:
            args:
                - special_case
            kwargs:
                special: True
        - describe:
            args:
                - generic
            kwargs:
                special: False

        :operation: boto3 client function name to find a rule for

        :returns: the matched rule's {args, kwargs} dict, or None if nothing matched
        """
        if self.service_name not in self.injected_args:
            return None

        for rule in self.injected_args[self.service_name]:
            rule_name = list(rule.keys())[0]
            if rule_name in operation:  # partial matches accepted
                return rule[rule_name]

        return None

    def _get_custom_args(self, operation) -> Tuple[list, dict]:
        """
        Locate the args and kwargs for a given operation from the serialized YAML structure.
        See _find_injected_rule for the matching rules.
        """
        args = []
        kwargs = {}
        if rule := self._find_injected_rule(operation):
            if rule["kwargs"]:
                kwargs.update(rule["kwargs"])
            if rule["args"]:
                args += rule["args"]

        return (args, kwargs)

    def _report_progress(self, description: str) -> None:
        """
        Advance the caller-supplied rich Progress task by one operation, and update
        status_text (if supplied) to show what was just tested. The task's own
        description is left alone - it stays a fixed-width service name - since
        updating it in place per-operation made the bar's row bounce/flicker as the
        text grew and shrank. Guarded by a lock since many worker threads call this
        concurrently. No-op if no progress/task_id was supplied.
        """
        if self.progress is None or self.task_id is None:
            return
        with self._progress_lock:
            self.progress.update(self.task_id, advance=1)
            if self.status_text is not None:
                self.status_text.plain = description

    def _print_diagnostic(self, message: str, style: str = "red") -> None:
        """
        Print a diagnostic message (connection timeouts, unhandled exceptions) safely
        alongside an active Live display. See the :console: param docstring above for
        why this can't just be a plain print().
        """
        if self.console is not None:
            self.console.print(message, style=style, markup=False)
        else:
            print(message, file=sys.stderr)

    def test_all_operations(self, client) -> List[OperationPermissions]:
        """
        Test all operations for the given client. We also inject args by pattern matching
        the service and operation against the injected_args dictionary. see the _get_custom_args
        docs for more information on the matching system.

        :client: boto3 client object

        :returns: List of OperationPermissions objects for each operation tested
        """
        results = []
        futures = {}

        for operation in self.operations:
            args, kwargs = self._get_custom_args(operation)
            if operation in self.dry_run_operations:
                # Force this regardless of what injected_args set - never trust a YAML
                # value here, since a False (or a typo/omission) would let a mutating
                # call through for real.
                kwargs["DryRun"] = True
            futures[
                self.executor.submit(
                    self.test_permission, operation, client, *args, **kwargs
                )
            ] = (operation, client.meta.region_name)

        for future in as_completed(futures):  # wait 5s per future before timeout
            (operation, region) = futures[future]
            self._report_progress(f"{self.service_name}->{operation} in {region}")
            try:
                results.append(future.result())
            except (
                botocore.exceptions.ConnectTimeoutError,  # pyright: ignore
                botocore.exceptions.EndpointConnectionError,  # pyright: ignore
            ):
                self._print_diagnostic(
                    f"[!] Connection timeout: {self.service_name}->{operation} in {region}"
                )
            except AttributeError as e:
                if not hasattr(client, operation):
                    # boto3 claimed this method existed (it's in
                    # method_to_api_mapping, which is where self.operations came
                    # from) but it genuinely doesn't - that's a real, fatal
                    # inconsistency worth stopping everything to investigate, not
                    # just this one operation.
                    raise e
                # The attribute exists; this AttributeError came from somewhere deep
                # inside actually executing the call (observed in the wild: a bug in
                # moto's own KMS mock for retire_grant hit None.startswith() - nothing
                # to do with boto3 lying about the method existing). Treat it like any
                # other unexpected exception rather than crashing the whole scan over
                # one operation.
                self._print_diagnostic(
                    f"[!] Oopsie woopsie :3, hit an unhandled exception at {self.service_name}->{operation} in {region}: {e}"
                )
            except Exception as e:
                self._print_diagnostic(
                    f"[!] Oopsie woopsie :3, hit an unhandled exception at {self.service_name}->{operation} in {region}: {e}"
                )

        return results

    def scan(self) -> Dict[str, OperationPermissionsByRegion]:
        """
        Scan all operations for the service and all regions, then translate the results to be grouped by region for easier analysis.
        The results are translated from the region being the primary key to the method being the primary key, this is done to maximize re-use of clients.

        Regions are scanned one at a time rather than submitted to self.executor -
        test_all_operations submits its own (usually much higher-cardinality)
        per-operation calls to that same executor, and submitting per-region tasks to
        it too meant a service with enough regions to fill every worker thread (e.g.
        S3, available in 34 regions vs MAX_WORKERS=30) would deadlock: every thread
        occupied by a region-level task blocked waiting on operation-level tasks that
        could never get a free thread to run on. Rate limiting is per-endpoint (each
        region is a separate one), so there's no throughput reason to run regions
        concurrently against a shared pool - each region's operations are still fully
        parallelized via self.executor.

        :returns: Dict with keys of AWS operation names and values of OperationPermissionsByRegion objects
        """
        operation_permissions = []
        operation_permissions_by_region = {}
        for client in self.clients:
            operation_permissions += self.test_all_operations(client)

        # Translate List of OperationPermissions into a list of OperationPermissionsByRegion
        for operation in operation_permissions:
            if operation.name not in operation_permissions_by_region.keys():
                operation_permissions_by_region[operation.name] = (
                    OperationPermissionsByRegion(
                        name=operation.name,
                        regions_tested=set(),
                        succeeded=[],
                        failed=[],
                        errored=[],
                    )
                )

            operation_permissions_by_region[operation.name].regions_tested.add(
                operation.region
            )

            match operation.status:
                case TestStatus.SUCCEEDED:
                    operation_permissions_by_region[operation.name].succeeded.append(
                        operation
                    )
                case TestStatus.FAILED:
                    operation_permissions_by_region[operation.name].failed.append(
                        operation
                    )
                case TestStatus.ERRORED:
                    operation_permissions_by_region[operation.name].errored.append(
                        operation
                    )

        return operation_permissions_by_region

    def pretty_print_scan(
        self, scan_results: Dict[str, OperationPermissionsByRegion], only_hits=True
    ) -> list:
        """
        Format scan and return str so we can handle the printing elsewhere.

        :scan_results: Dict with keys of AWS operation names and values of OperationPermissionsByRegion objects
        """
        formatted_results = []
        for operation, results in scan_results.items():
            if only_hits:
                results_marker_map = {
                    "+": results.succeeded,
                }
            else:
                results_marker_map = {
                    "+": results.succeeded,
                    "-": results.failed,
                    "!": results.errored,
                }
            for marker, test_results in results_marker_map.items():
                regions = set(test.region for test in test_results)
                if regions:
                    if regions == results.regions_tested:
                        formatted_results.append(
                            f"[{marker}] {operation} - All Regions"
                        )
                    else:
                        formatted_results.append(
                            f"[{marker}] {operation} - {','.join(regions)}"
                        )

        return formatted_results  # TODO consider just str appending the whole time and abandon the list
